[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "combat>=0.3.3",
    "data>=0.4",
    "django-locations-base>=0.3.4",
    "player>=0.6.1",
]
